<a href="https://colab.research.google.com/github/kizimaolivia-afk/Coursework2-repo/blob/main/W05_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CML3112 A5 — Pandas investigation
Complete the tasks below in this notebook. The short instructions follow.

<!-- assignment-workflow -->
# CML3112 A5 — Pandas investigation

**Submit:** ONE completed assignment notebook (.ipynb).

**Deadline:** 13 October 2026, 11:00 Kampala. The live form shows any later change.

## 1. Start

Open **W05_student.ipynb**. Keep these supporting files beside it: campus_energy.csv.

In Colab: File → Open notebook → Upload. Add any supplied CSV files through the Files sidebar. Save your own copy in Drive.

No grading scripts are needed. Complete every task; your uploaded notebook is marked automatically after submission.

## 2. Work down the notebook

1. Set STUDENT_ID to your own Student Registration Number, keeping quotes and slashes. Keep COHORT="CML3112".
2. Answer each numbered task immediately below its prompt. Keep the required names exactly as shown.

3. Complete every task. The marks beside the tasks total **20**. No separate report or written-evidence section is required.

The Repository URL field is optional for this assignment; a GitHub repository is not required.

Six tasks: load the data, count meters, calculate cost_per_kwh, filter high_use, calculate the mean and find peak_building. Create cost_per_kwh before filtering.

## 3. Check and save

Restart and run all cells from the top. Fix errors, then download/save the completed notebook. For the filename only, replace slashes in your registration number with underscores and add _W05.ipynb.

## 4. Hand in

Open your cohort’s form below. Enter your Student Registration Number. Choose **Add file → Upload**, attach the required file(s), then press **Submit**. Keep the confirmation.

For individual work, leave Team ID blank. Each file must be at most 10 MB. A replacement before the deadline must contain the complete file set again.

**Do not submit:** the ZIP, guided_practice.ipynb, raw CSVs or helper scripts.

**Submission link:** https://docs.google.com/forms/d/e/1FAIpQLSeP_Eykf3YDYN_6sbB5to0B3LX14fsujEVPhsp8UezRZXTNGw/viewform

## Help only if needed

Need help opening, saving or uploading? Use STUDENT_HOW_TO.md only for the step you are stuck on. It is a reference, not extra homework.

In [ ]:
STUDENT_ID="24_351_BSCE_S"
COHORT="CML3112"

## q1: 3 marks
Load campus_energy.csv into a DataFrame called df.

In [2]:
import pandas as pd

df = pd.read_csv("campus_energy.csv")
df.head()

  meter_id     building        block    month   kwh  cost_ugx
0    M-001  Kabojja Lab  Engineering  2026-01  4820   3374000
1    M-001  Kabojja Lab  Engineering  2026-02  5310   3717000
2    M-001  Kabojja Lab  Engineering  2026-03  6140   4298000
3    M-002   Workshop A  Engineering  2026-01  7420   5194000
4    M-002   Workshop A  Engineering  2026-02  7980   5586000

## q2: 3 marks
Set n_meters to the number of distinct meters in the file.

In [3]:
n_meters = df["meter_id"].nunique()
print(n_meters)

8

## q3: 4 marks
Add a column cost_per_kwh to df, equal to cost_ugx / kwh.

In [4]:
df["cost_per_kwh"] = df["cost_ugx"] / df["kwh"]
df.head()

  meter_id     building        block    month   kwh  cost_ugx  cost_per_kwh
0    M-001  Kabojja Lab  Engineering  2026-01  4820   3374000         700.0
1    M-001  Kabojja Lab  Engineering  2026-02  5310   3717000         700.0
2    M-001  Kabojja Lab  Engineering  2026-03  6140   4298000         700.0
3    M-002   Workshop A  Engineering  2026-01  7420   5194000         700.0
4    M-002   Workshop A  Engineering  2026-02  7980   5586000         700.0

## q4: 4 marks
Set high_use to the rows of df where kwh is greater than 5000. Do this after q3 so the derived column comes along.

In [5]:
high_use = df[df["kwh"] > 5000].copy()
high_use

,meter_id,building,block,month,kwh,cost_ugx,cost_per_kwh
1,M-001,Kabojja Lab,Engineering,2026-02,5310,3717000,700.0
2,M-001,Kabojja Lab,Engineering,2026-03,6140,4298000,700.0
3,M-002,Workshop A,Engineering,2026-01,7420,5194000,700.0
4,M-002,Workshop A,Engineering,2026-02,7980,5586000,700.0
5,M-002,Workshop A,Engineering,2026-03,8115,5680500,700.0
9,M-004,Hostel Block C,Residence,2026-01,9240,6006000,650.0
10,M-004,Hostel Block C,Residence,2026-02,9880,6422000,650.0
11,M-004,Hostel Block C,Residence,2026-03,10410,6766500,650.0
15,M-006,Server Room,Central,2026-01,5605,3923500,700.0
16,M-006,Server Room,Central,2026-02,5710,3997000,700.0
17,M-006,Server Room,Central,2026-03,5890,4123000,700.0
21,M-008,Hostel Block D,Residence,2026-01,8630,5609500,650.0
22,M-008,Hostel Block D,Residence,2026-02,8990,5843500,650.0
23,M-008,Hostel Block D,Residence,2026-03,9125,5931250,650.0

## q5: 3 marks
Set mean_cost_per_kwh to the mean of the cost_per_kwh column.

In [6]:
mean_cost_per_kwh = df["cost_per_kwh"].mean()
print(mean_cost_per_kwh)

687.5

## q6: 3 marks
Set peak_building to the name of the building with the highest total kwh.

In [7]:
peak_building = df.groupby("building")["kwh"].sum().idxmax()
print(peak_building)

Hostel Block C

Restart and Run All, then save your named notebook. Your uploaded notebook is marked automatically after submission.