<a href="https://colab.research.google.com/github/kizimaolivia-afk/Coursework2-repo/blob/main/Week04_guided_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 4 guided practice
CML3112. Follow the lecturer’s PowerPoint in this order. This notebook contains worked examples, not your graded upload.

Extract the student ZIP and keep its files together. For Weeks 4 and 5, upload the supplied CSV into the Colab runtime before running the file-reading example. Small worked datasets are invented; the CSV inspection uses your supplied file.

## Today’s learning
*PowerPoint slide 2*

Read lists and dictionary fields.

Trace a loop, read CSV rows and calculate summaries.

## Connection to the previous lesson
*PowerPoint slide 3*

Week 3 introduced values, function inputs and results, conditions and list positions. Now we repeat a calculation across records, then organise those records by keys.

## Why this week’s tools are needed
*PowerPoint slide 4*

Sensor readings arrive as records in a CSV file. We first learn the Python collections and loops needed to read those records and summarise them.

## List and index
*PowerPoint slide 5*


**List and index** — A list holds values in order: [2, 4, 6]. Square brackets select a position. readings[0] selects the first item, 2.

## A list position starts at zero
*PowerPoint slide 6*

In [2, 4, 6], position 0 holds 2.

Position 1 holds 4. Position 2 holds 6.

There is no position 3 in this three-item list.

## Read list operations
*PowerPoint slide 7*


**append and len** — readings.append(8) adds 8 to the end of the list. len(readings) counts its items. The dot selects an operation belonging to that object; parentheses call it.

**Slice** — readings[1:3] selects positions 1 and 2. The stop position 3 is excluded. A slice produces a new list; it does not remove items from the original.

## A list stores items in order
*PowerPoint slide 8*



[] builds a list. Positions start at zero. The slice stops before position 3.

In [ ]:
readings = [2, 4, 6]
print(readings[0])
readings.append(8)
print(len(readings))
print(readings[1:3])

## Trace the list changes
*PowerPoint slide 9*



| Instruction | List afterwards | Displayed output |
| --- | --- | --- |
| readings = [2, 4, 6] | [2, 4, 6] | Nothing yet |
| print(readings[0]) | [2, 4, 6] | 2 |
| readings.append(8) | [2, 4, 6, 8] | Nothing yet |
| print(readings[1:3]) | [2, 4, 6, 8] | [4, 6] |

len reports 4 after append. A slice excludes its stop position and leaves the original list intact.

## A loop repeats instructions
*PowerPoint slide 10*

A loop runs a block more than once. One execution of the block is called an iteration.

for takes one item at a time from a collection. Use it when each item needs the same action.

while repeats while a condition stays True. Use it when a condition controls repetition. We will trace each kind before using it in a calculation.

## Read every part of a for header
*PowerPoint slide 11*

In for reading in readings:, for introduces repetition, reading names the current item, and readings is the collection to visit.

in connects the current-item name to that collection. The colon begins the loop body. Four spaces mark each instruction that repeats.

reading is a name we choose; it is assigned the next item automatically. It is not the same name as readings. After the last item, execution leaves the loop.

## Visit each item without calculating
*PowerPoint slide 12*



Output: 2; 4; 6; finished

In [1]:
readings = [2, 4, 6]
for reading in readings:
    print(reading)
print("finished")

2
4
6
finished

In [3]:
readings = [2, 4, 6]
for reading in readings:
  if reading > 2:
    print(reading)
print("finished")

4
6
finished

## Trace the for loop item by item
*PowerPoint slide 13*



| Step | Current reading | Action |
| --- | --- | --- |
| First item | 2 | Print 2 |
| Second item | 4 | Print 4 |
| Third item | 6 | Print 6 |
| No items left | No new item | Leave loop; print finished |

An empty list runs the body zero times. It still reaches the outside line.

## Updating a counter inside a loop
*PowerPoint slide 14*

A counter records how many times an event happens. Set count = 0 before the loop, then count = count + 1 inside it.

count += 1 is a shorter spelling for that numeric update. Similarly, total += reading means total = total + reading.

The initial value belongs outside the loop. Resetting count to zero inside every iteration loses the earlier count.

## Count the visited items
*PowerPoint slide 15*



Output: 3

In [6]:
count = 0
for reading in [2, 4, 6]:
    count += 1
print(count)

3

In [7]:
count = 1
for reading in [2, 4, 6]:
    count += 1
print(count)

4

In [11]:
student_count = 0
for student in ["Emma","Olivia","Renitah"]:
    student_count += 1
print(student_count)

3

## Accumulator
*PowerPoint slide 16*


**Accumulator** — A running total. Set it to zero before the loop, add inside the loop, and read the final total afterward.

## A loop repeats an indented block
*PowerPoint slide 17*

for reading in readings: takes one item at a time.

The colon starts the block. Four spaces show which lines repeat.

A running total must start at zero before the loop.

## A mean uses a total and a count
*PowerPoint slide 18*

Start the total at 0. Add 2, then 4, then 6.

The final total is 12. The count is 3.

12 / 3 gives the mean 4. An empty list needs a separate rule.

## A loop changes the running total
*PowerPoint slide 19*


See the illustration on this PowerPoint slide.

This illustration uses six separate readings. Next we trace the smaller list [2, 4, 6] using the same running-total rule.

## Tracing the loop
*PowerPoint slide 20*



| Step | reading | total after addition |
| --- | --- | --- |
| Before loop | — | 0 |
| First | 2 | 2 |
| Second | 4 | 6 |
| Third | 6 | 12 |

There are three readings.

## Lists loops and records in Python
*PowerPoint slide 21*



Read top to bottom. Run the complete example in the matching practice notebook.

In [12]:
readings = [2, 4, 6]
total = 0
for reading in readings:
    total = total + reading
mean = total / len(readings)
print(mean)

4.0

## Lists loops and records results
*PowerPoint slide 22*

4.0

## The built-in summary functions
*PowerPoint slide 23*



| Function | Question it answers | For [2, 4, 6] |
| --- | --- | --- |
| len | How many items? | 3 |
| sum | What is their total? | 12 |
| min | Which is smallest? | 2 |
| max | Which is largest? | 6 |

These functions already exist in Python. min and max need at least one item unless an explicit default is supplied.

## Built-in summaries of a list
*PowerPoint slide 24*



Output: 12, 3, 2, 6. sum totals; len counts; min and max select the smallest and largest.

In [13]:
readings = [2, 4, 6]
print(sum(readings))
print(len(readings))
print(min(readings))
print(max(readings))

12
3
2
6

## A while loop checks before each repetition
*PowerPoint slide 25*

while count < 3: tests the condition before entering its indented block. True enters the block; False skips it and continues after the loop.

At the end of the body, return to the condition and test again. Unlike for, while does not automatically move to the next list item.

Something must make the condition become False, or the loop may continue indefinitely. In our example, count increases on every iteration.

## A while loop with a stopping condition
*PowerPoint slide 26*



Output: 0; 1; 2; finished

In [14]:
count = 0
while count < 3:
    print(count)
    count = count + 1
print("finished")

0
1
2
finished

In [15]:
count = 0
while count < 3:
    print(count)
    count = count + 2
print("finished")

0
2
finished

## Trace the while condition and update
*PowerPoint slide 27*



| count before test | count < 3 | Body and next count |
| --- | --- | --- |
| 0 | True | Print 0; update to 1 |
| 1 | True | Print 1; update to 2 |
| 2 | True | Print 2; update to 3 |
| 3 | False | Skip body; print finished |

If count starts at 3, the body runs zero times. The condition is tested first.

## Preventing an endless loop
*PowerPoint slide 28*

If the update is missing, count remains 0. The question 0 < 3 stays True, so the body keeps running.

In Colab, click the running cell’s stop button or use Runtime → Interrupt execution. Fix the condition or update before running again.

Do not run an intentionally endless example. Trace the unchanged value on the slide to see why it would fail.

## Choosing if for or while
*PowerPoint slide 29*



| Construct | Purpose | When it finishes |
| --- | --- | --- |
| if / else | Choose a path once | After the chosen block |
| for | Visit supplied items | When items are exhausted |
| while | Repeat while True | When condition becomes False |

A condition alone does not imply repetition: if tests once; while tests again after its body.

## range supplies a sequence of integers
*PowerPoint slide 30*

range(3) supplies 0, 1 and 2. The stop value 3 is excluded. range(1, 4) supplies 1, 2 and 3.

Use range with for when a numbered repetition is useful. The loop still works by taking the next supplied item.

range(0, 6, 2) uses a step of 2 and supplies 0, 2, 4. A step is the change between successive numbers; it cannot be zero.

## Repeat with range
*PowerPoint slide 31*



Output: 1; 2; 3

In [16]:
for attempt in range(1, 4):
    print(attempt)

1
2
3

## continue and break change a loop’s path
*PowerPoint slide 32*

continue skips the rest of the current iteration, then starts the next iteration. It does not end the whole loop.

break exits the nearest enclosing loop immediately. Execution resumes after that loop.

Put the condition inside the loop with four spaces. Its action is inside that condition with eight spaces: an indented block inside another block.

## Skip one item using continue
*PowerPoint slide 33*



Output: 2; 6

In [17]:
for reading in [2, -1, 6]:
    if reading < 0:
        continue
    print(reading)

2
6

## Stop at one item using break
*PowerPoint slide 34*



Output: 2

In [18]:
for reading in [2, -1, 6]:
    if reading < 0:
        break
    print(reading)

2

## Trace the two loop controls
*PowerPoint slide 35*



| Input | continue version | break version |
| --- | --- | --- |
| 2 | Print 2 | Print 2 |
| -1 | Skip its print | Exit loop |
| 6 | Print 6 | Never visited |

Use continue only when skipping is justified by the stated data rule; do not silently discard evidence.

## A dictionary is a record with named fields
*PowerPoint slide 36*

record = {"unit": "A", "reading": 4} stores two key–value pairs. Keys name fields; values hold the information.

Braces enclose the dictionary. A colon separates each key from its value and a comma separates pairs. Each key is unique.

record["reading"] returns 4. Unlike a list position, "reading" names the field we want.

## A missing dictionary key and get
*PowerPoint slide 37*

record["reading"] requests a known field. If that key does not exist, square-bracket lookup raises KeyError.

record.get("missing", 0) asks for that key with a fallback: return 0 if it is absent. This does not add a new key.

The second input is the fallback value. Use a fallback only when the task defines what missing information should mean.

## Reading and updating a dictionary
*PowerPoint slide 38*



Output: 4, then 6, then 0. get uses the fallback only when that key is absent.

In [19]:
record = {"unit": "A", "reading": 4}
print(record["reading"])
record["reading"] = 6
print(record["reading"])
print(record.get("missing", 0))

4
6
0

## Tuples and unpacking
*PowerPoint slide 39*

A tuple stores items in order. point = (2, 3) stores two coordinates; point[0] is 2. You cannot reassign point[0].

x, y = point gives the first item to x and the second to y. This is unpacking; the number of names must match the number of items.

A tuple prevents replacing its positions. It does not freeze the contents of a mutable object stored inside it.

## Unpacking a pair
*PowerPoint slide 40*



Output: 2, then 3.

In [ ]:
point = (2, 3)
x, y = point
print(x)
print(y)

## A set remembers distinct items
*PowerPoint slide 41*

A set is useful when the question is “Have we seen this ID?” It keeps one instance of each distinct item.

seen = set() creates an empty set. seen.add("A") adds an item. "A" in seen asks whether it is present.

Do not use a set when position or repeated readings matter. Sets cannot be indexed. {} creates an empty dictionary, not an empty set.

## Set membership and repeated IDs
*PowerPoint slide 42*



Output: 1, True, False. Adding the same ID twice keeps one distinct ID.

In [ ]:
seen = set()
seen.add("A")
seen.add("A")
print(len(seen))
print("A" in seen)
print("B" in seen)

## How the four collections differ
*PowerPoint slide 43*



| Collection | Find an item by | Repeats / changes |
| --- | --- | --- |
| list | Position: values[0] | Repeats allowed; items change |
| dict | Key: record["reading"] | Keys unique; values change |
| tuple | Position: point[0] | Repeats allowed; positions fixed |
| set | Membership: "A" in seen | Distinct items; add or remove |

Choose by the question: ordered readings, named fields, fixed positions, or distinct IDs.

## Dictionary items and two loop names
*PowerPoint slide 44*

record.items() provides each key with its value as a pair. The loop unpacks each pair into the names key and value.

for key, value in record.items(): repeats the indented body for each field. Use .items() when both the label and its value are needed.

## Looping through named fields
*PowerPoint slide 45*



Output: unit A, then reading 6. The dictionary preserves insertion order.

In [ ]:
record = {"unit": "A", "reading": 6}
for key, value in record.items():
    print(key, value)

## A position and a key find different things
*PowerPoint slide 46*


See the illustration on this PowerPoint slide.

Both examples return 4. Explain how each lookup finds it.

## CSV and header
*PowerPoint slide 47*


**CSV and header** — CSV means comma-separated values. One line usually represents one record; a header names the columns. CSV numbers arrive as text and may need float conversion.

## One record at a time
*PowerPoint slide 48*

A CSV is a text table with a header row.

DictReader uses that header for dictionary keys.

CSV cells begin as text, even when they look numeric.

float("2.5") converts text into the number 2.5.

## A CSV file has a header and text values
*PowerPoint slide 49*



| CSV line | Dictionary meaning |
| --- | --- |
| unit,reading | Two field names |
| A,2.5 | {"unit": "A", "reading": "2.5"} |
| B, | {"unit": "B", "reading": ""} |

An empty field is empty text. Check the task’s rule before converting it.

## A CSV row becomes a dictionary
*PowerPoint slide 50*

The header gives field names, such as unit and reading.

csv.DictReader returns one dictionary for each data row.

The value "2.5" starts as text. float("2.5") makes the number 2.5.

## with and import
*PowerPoint slide 51*


**with and import** — import makes library tools available. with open(...) opens a file for a block and closes it afterward. A filename must match an existing file in the working folder.

## Your cohort data
*PowerPoint slide 52*

site_inspection_log.csv

Summarise crack_width_mm (millimetres); group by structure_id.

Read the issued task’s blank-value and threshold rules before calculating.

## Read the supplied CSV in four steps
*PowerPoint slide 53*

Place site_inspection_log.csv beside the notebook, or upload it in Colab’s Files panel.

import csv loads the CSV tools. newline="" lets the reader handle line endings. DictReader uses the header as dictionary keys.

list(...) collects the rows while the file is open. We inspect the first row and the count; the later assignment calculations are your work.

## What with open as source does
*PowerPoint slide 54*

open("file.csv", newline="") opens a text file for reading. Use the actual supplied filename, including its .csv extension.

with manages the open file. as source gives that file object a name. Indented lines use it while it is open; leaving the block closes it.

csv.DictReader(source) reads rows using the header names as keys. list(...) collects those rows into memory before the file closes.

## Open a real CSV and inspect its first row
*PowerPoint slide 55*



Read the actual keys and text values. Check the uploaded filename if Python reports FileNotFoundError.

In [20]:
import csv
with open("/content/site_inspection_log.csv", newline="") as source:
    rows = list(csv.DictReader(source))
print(rows[0])
print(len(rows))

{'structure_id': 'B1', 'span_m': '12', 'inspection_date': '2026-03-01', 'crack_width_mm': '0.087', 'defect_rating': '1', 'inspector_id': 'I1'}
300

In [21]:
import pandas as pd

In [24]:
data = pd.read_csv("/content/site_inspection_log.csv")

In [25]:
data.head(10)

,structure_id,span_m,inspection_date,crack_width_mm,defect_rating,inspector_id
0,B1,12,2026-03-01,0.087,1,I1
1,B1,12,2026-03-02,0.112,1,I2
2,B1,12,2026-03-03,0.080,1,I3
3,B1,12,2026-03-04,0.087,2,I4
4,B2,13,2026-03-05,0.148,2,I1
5,B2,13,2026-03-06,0.127,2,I2
6,B2,13,2026-03-07,0.132,2,I3
7,B2,13,2026-03-08,0.108,2,I4
8,B3,14,2026-03-09,0.191,2,I1
9,B3,14,2026-03-10,0.173,2,I2

In [26]:
data.tail()

,structure_id,span_m,inspection_date,crack_width_mm,defect_rating,inspector_id
295,B2,13,2026-03-16,0.179,3,I4
296,B3,14,2026-03-17,0.146,2,I1
297,B3,14,2026-03-18,0.183,2,I2
298,B3,14,2026-03-19,0.148,2,I3
299,B3,14,2026-03-20,0.160,3,I4

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   structure_id     300 non-null    object
 1   span_m           300 non-null    int64
 2   inspection_date  300 non-null    object
 3   crack_width_mm   297 non-null    float64
 4   defect_rating    300 non-null    int64
 5   inspector_id     300 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 14.2+ KB

## A list of dictionaries
*PowerPoint slide 56*

A record holds named fields for one observation. A list of records holds several observations in order.

records[0] selects the first dictionary. records[0]["reading"] then selects that dictionary’s reading field.

for row in records takes one dictionary at a time. row["reading"] retrieves that observation’s field; float converts numeric text when needed.

## A record and a growing list
*PowerPoint slide 57*

Braces pair a key with its value. append adds one value to the end of a list.

The same pattern works after reading a CSV row.

## A record and a growing list in Python
*PowerPoint slide 58*



Read top to bottom. Run the complete example in the matching practice notebook.

In [ ]:
records = [{"sensor": "A", "reading": "2.5"},
           {"sensor": "B", "reading": "3.5"}]
values = []
for row in records:
    values.append(float(row["reading"]))
print(values)

## Skip a blank before converting text
*PowerPoint slide 59*

An empty text field is "". The comparison != means “not equal to”. Only convert a value after the blank check passes.

In this example, values records valid numbers only. Its length is the valid count; the group summaries must use the same valid-record policy.

## Collect only the recorded numbers
*PowerPoint slide 60*



Expected: 2 [2.5, 3.5]. A blank is missing, not a recorded zero.

In [ ]:
text_values = ["2.5", "", "3.5"]
values = []
for text in text_values:
    if text != "":
        values.append(float(text))
print(len(values), values)

## Membership in a dictionary
*PowerPoint slide 61*

group in totals asks whether group is already a dictionary key. group not in totals asks whether that key is absent.

Before adding to a new group, create its total with totals[group] = 0. Then add the current record’s reading.

The outer for visits records. The inner if runs only for a new group. The addition after the if runs for every record.

## Summaries for separate groups
*PowerPoint slide 62*

A dictionary can hold one running total for each group.

An absent key needs an initial zero.

Then add the reading to that group.

To calculate group means, keep a matching count and divide each group total by its own count.

## Summaries for separate groups in Python (1/2)
*PowerPoint slide 63*



Read top to bottom. Run the complete example in the matching practice notebook.

In [ ]:
records = [{"group": "A", "reading": 2},
           {"group": "A", "reading": 4},
           {"group": "B", "reading": 9}]
totals = {}
for row in records:
    group = row["group"]
    if group not in totals:
        totals[group] = 0
    totals[group] = totals[group] + row["reading"]
print(totals)

## A group mean needs its own count
*PowerPoint slide 65*

The preceding loop calculated a total for each group. Count records in those same groups, then divide each group total by its own count.

items() supplies the group name and its total together. We use small invented records, not the assignment’s answers.

## From group totals to group means
*PowerPoint slide 66*



Expected: A has mean 3.0 and B has mean 9.0. Each group uses its own denominator.

In [ ]:
counts = {}
for row in records:
    group = row["group"]
    counts[group] = counts.get(group, 0) + 1
means = {}
for group, total in totals.items():
    means[group] = total / counts[group]
print(means)

## When numeric text cannot be converted
*PowerPoint slide 67*

float("bad") raises ValueError: the text does not represent a number. An exception interrupts ordinary execution.

try contains the operation that might fail. except ValueError runs only for that named failure. Indentation shows the two blocks.

## Catch one expected conversion failure
*PowerPoint slide 68*



Expected: None. The assignment specifies which invalid records to skip; do not invent a replacement number.

In [ ]:
text = "bad"
try:
    reading = float(text)
except ValueError:
    reading = None
print(reading)

## Trace conversion success and failure
*PowerPoint slide 69*



| Text supplied | try block | Result after except |
| --- | --- | --- |
| "2.5" | float succeeds; skip except | 2.5 |
| "bad" | float raises ValueError | None assigned by except |

Only the named conversion failure is handled. Do not use except: pass to hide unrelated errors.

## Revision example and answer
*PowerPoint slide 70*

Example: Add 8 to the list. Trace the new total and count before running. What happens if total = 0 is moved inside the loop?

Answer: Total 20, count 4, mean 5.0. Resetting inside the loop discards previous additions and leaves only the last value in total.

## Preparing for the assignment
*PowerPoint slide 71*

Open the issued W04 notebook and its cohort CSV.

Compute the requested valid_count, mean_reading, above_limit and group_means using the exact names in the notebook.

First identify the correct field and its unit.

Keep the CSV beside the notebook locally or upload it into the Colab runtime.

## Preparing for the assignment continued
*PowerPoint slide 72*

The written interpretation is practice.

## Counting every record honestly
*PowerPoint slide 73*

DictReader already consumes the header; skipping its first yielded row skips real data.

A string such as "unknown" cannot be converted to float.

Catch the expected conversion error, count and record it, then continue under a stated policy.

Inspect whether skipped rows share a source before reporting a mean.

## Counting every record honestly continued
*PowerPoint slide 74*

A sample summary describes observed records, not every possible operating condition.

## Continue with your issued assignment
Open the assignment notebook named in 00_START_HERE.txt. Keep required function names, return types and units. guided_practice.ipynb is not a graded upload. Use SUBMIT_HERE.txt for the correct submission link.